stock-update:
  frequency:
    seconds: 5

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080


logging:
  level:
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.apache.kafka.clients.producer.ProducerConfig: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: ERROR
    org.apache.kafka.clients.admin.AdminClientConfig: ERROR

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/demo
      database: demo
  application:
    name: stock-prices
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "*"
  cloud:
    stream:
      function:
        definition: stockTickSupplier;stockTickConsumer;candleStickConsumer
      default-binder: kafka
      bindings:
#        aggregate-out-0:
#          destination: transformed
#        aggregate-in-0:
#          destination: testtock
        candleStickConsumer-in-0:
          destination: testtock
          group: candleStickConsumer-group
        stockTickConsumer-in-0:
          destination: testtock
          group: stockTickConsumer-group
        stockTickSupplier-out-0:
          destination: testtock
